version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "org.jetbrains.dokka"
        # handled manually due to breaking changes
  - package-ecosystem: "gradle"
    directory: "/buildSrc/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

