[versions]
# BLEEDING EDGE VERSIONS 🩸 (DON'T DOWNGRADE)
kotlin = "2.2.0"
ksp = "2.2.0-2.0.2"
agp = "8.12.0"
hilt = "2.57"
compose-compiler = "1.6.0"
java-toolchain = "24"
java-target = "21"     # Bytecode target (Kotlin limitation)

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
