[versions]
# These MUST be updated for Java 24
ksp = "2.2.0-2.0.2"
dokka = "2.0.0"  # Up from 1.9.x
detekt = "1.23.8"  # Ensure latest
spotless = "7.2.1"  # Ensure latest
gradle = "9.0.0"  # You already have this
kotlin = "2.2.0"  # You already have this
agp = "8.12.0"  # You already have this

# Make sure these support Java 24
accompanist = "0.37.3"  # Update if needed
hilt = "2.57"
compose-compiler = "1.6.0"
java-toolchain = "24"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
