name: Debug APK Build

on:
  workflow_dispatch:

jobs:
  build-apk-debug:
    runs-on: ubuntu-latest
    env:
      JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '24'

      - name: Show environment info
        run: |
          echo "PATH=$PATH"
          java -version
          uname -a
          env

      - name: Enable runner debug logging
        run: |
          echo "::debug::Enabling shell tracing"
          set -x

      - name: chmod x gradlew
        run: chmod +x ./gradlew
      
      - name: Build APK with Gradle debug
        run: |
          ./gradlew assembleDebug --stacktrace --info --debug

      - name: List APK output files
        run: |
          find . -type f -name "*.apk"
